### PR TITLE
Fixing Dividend "Next" Api

### PR DESCRIPTION
**Pull request by longpshorn**
The change I submitted this morning that was working for the Dividend endpoint is no longer working. Either I was seeing things or IEXCloud updated their api today.

### CODE REVIEW

**Review by JamiePrentice — COMMENTED** [review]
That’s strange, I’ve not ran those tests after that change went in. I’m not at my pc at the moment but a glance I’d think that that should work.

Does the one for splits also fail tests?

**Comment by vslee** [comment]
The Split still works. I think the problem is not that the API changed on IEX's side. The reason the Dividend test is now failing is because the 'next' dividend for AAPL is now null. So when that's the case, IEX returns an empty array []. Split still works bc it is testing the symbol AMPL, which has a 'next' split of 5/12/2020 and is thus not null.
AAPL changed bc according to this [site](https://www.dividendchannel.com/symbol/aapl/next-dividend-date/):

> AAPL Next Dividend Date Projection
> Last known ex-date: 05/08/20
> Last known frequency: Quarterly
> Last known quarterly dividend: 0.82
> Expected annual yield: 1.08%
> Typical ex-date schedule:
> February 8th
> May 11th
> August 10th
> November 8th
> Predicted Next Dividend Ex-Date For AAPL: August 10th

Which happens to be today. So it went from having a next Dividend of today, to not having a next one anymore (as today is now over).

**Comment by vslee** [comment]
Thus, we should not get rid of the code you added this morning. As we will still need it when the 'next' is not null.
I'll post an alternative solution to see what you guys think

**Comment by JamiePrentice** [comment]
So the code may be fine, but the test company isn't? An option could be to try ZIEXT the test company.

**Comment by vslee** [comment]
No, the code does need to be updated. I have put the alternative solution at #41.
I did try ZIEXT but that does not seem to be a valid company. The plus side is that I did discover a different error message that IEX sends ("Unknown Company") and have added the ability to handle that msg.

**Comment by longpshorn** [comment]
Yes, your solution looks good to me. I saw the same thing with the Unknown Symbol so glad you added that error as well.

**Pull request closed without merging**
