### PR TITLE
First Pass at removing deprecated legacy methods.

### PR DESCRIPTION
**Pull request by JamiePrentice**
- Removed all tests, interface and methods that were ignored due to no longer existing.
- Removed all methods where tests were returning forbidden.

### CODE REVIEW

**Comment by vslee** [comment]
Thanks for removing the deprecated legacy endpoints. I am not sure what IEX is doing with the Cloud DEEP Trade Break and DEEP Trading Status endpoints though. I can see that they just return "forbidden" when running the tests. Yet, they still exist on the IEX Cloud documentation?

**Comment by vslee** [comment]
I did a quick search through the docs and [IEX's GH Issues](https://github.com/iexg/IEX-API/issues?q=deep) but could not find any guidance from them what their future plans are. I do see that there are other [broken endpoints](https://github.com/iexg/IEX-API/issues/1467) they have not addressed yet. I think perhaps they are overwhelmed. It is possible that in the future, they will fix these two Cloud DEEP endpoints. What do you think about leaving them for now and seeing if they pop back up in the future?

**Comment by JamiePrentice** [comment]
@vslee I'm happy to leave them, I'd quite like to get the solution in a state where all of the tests are passing. So instead of deleting them, I'll flag them as ignored. I'll close this PR and do it in a fresh one, no point in cluttering the log.

**Comment by vslee** [comment]
> a state where all of the tests are passing

Don't make me laugh

**Pull request closed without merging**
