### PR TITLE
Adding CryptoBook Streaming 

### LINKED ISSUE #58: Add DEEP book streaming for US Stocks and Crypto
Hey All,

love this package! Please could you add DEER Book calls for US Stocks and Crypto which is mentioned here in the API description:

https://iexcloud.io/docs/api/

curl --header 'Accept: text/event-stream' https://cloud-sse.iexapis.com/stable/deep?token=YOUR_TOKEN&symbols=twtr&channels=book

curl --header 'Accept: text/event-stream' https://cloud-sse.iexapis.com/stable/cryptoBook\?symbols\=btcusd\&token\=YOUR_TOKEN

This would be awesome!
Thank you

### PR DESCRIPTION
**Pull request by JamiePrentice**
For #58 

- Added SSE Streaming for Crypto Book @ https://iexcloud.io/docs/api/#cryptocurrency-book
- Reordered Service / IService to be in order of the IEXCloud Docs.
- Fixed some minor doc inconsistencies.

### CODE REVIEW

**Review by vslee — APPROVED** [review]

**Comment by vslee** [comment]
LGTM, ok to merge

**Comment by vslee** [comment]
I am planning on pushing another NuGet tomm, if there are no objections from @JamiePrentice, @amine-mejaouel, or @longpshorn. 
For the version number, I am leaning towards 2.1.0. While there are some breaking changes in this release, they are minor compared to the ones in 2.0.0. Also, there will be additional breaking changes in the next version as well. While we can technically increment the major version number for each, I don't want to be seen as inflating the versions every month. We'll have gone from 1.2 to 4.0 within in a couple of months. 
Any opinions?

**Comment by longpshorn** [comment]
No objections from me. I haven't been as involved as of late, but I tend to agree with the minor version bump instead of a major one. If I recall, one of the main breaking changes was the namespace reorganization, but that was a pretty quick / easy fix and I don't think it really warrants a major version change. Probably does warrant some communication about the change though.

**Comment by JamiePrentice** [comment]
No objections here either, this last batch is mostly the addition of endpoints as opposed to restructuring of existing ones. 

@vslee what are the additional breaking changes that you foresee coming?

Things on my to look into list:
- That pesky premium endpoint that returns PDFs. https://iexcloud.io/docs/api/#valuengine
- Looking into the rules engine and seeing it it was feasible - https://iexcloud.io/docs/api/#rules-engine-beta
- I saw mentioned somewhere considering using System.Json / System.Text.Json in place of newtonsoft. And in a similar vein perhaps switching the streaming client to SignalR.

**Comment by vslee** [comment]
I'm thinking that once we switch to System.Json, there may be an opportunity to create JsonParsers that can automatically parse the longs directly into DateTimes and TimeStamps instead of having the user having to call an extension method. 
Changing dependencies such as Json parser or streaming client might also be considered a breaking change (although a very minimal one). This is bc the dependencies are transitive and ppl may have depended on one previously through the package. 
Overall, nothing major breaking planned.

**Pull request merged**
