### PR TITLE
Made more of the properties for Advanced Stats and Key Stats nullable

### PR DESCRIPTION
**Pull request by tmccart1**
Making more of the properties nullable to avoid JSON parsing exceptions.

### CODE REVIEW

**Review by vslee — APPROVED** [review]

**Comment by tmccart1** [comment]
HI @vslee , is there any chance you can make a new Nuget version with these recent changes?

**Comment by vslee** [comment]
Okay, you can try 2.4.1 now

**Comment by tmccart1** [comment]
Excellent, thank you @vslee !

**Comment by tmccart1** [comment]
@vslee , I found another error in Key Stats...

System.Text.Json.JsonException: {"week52change":-0.023,"week52high":10.48,"week52low":9.75,"marketcap":884795625,"employees":null,"day200MovingAvg":9.92,"day50MovingAvg":9.92,"float":null,"avg10Volume":560308.6,"avg30Volume":442554.08,"ttmEPS":null,"ttmDividendRate":null,"companyName":"Artius Acquisition, Inc.","sharesOutstanding":90562500,"maxChangePercent":-0.023,"year5ChangePercent":-0.023,"year2ChangePercent":-0.023,"year1ChangePercent":-0.023,"ytdChangePercent":-0.023,"month6ChangePercent":-0.023,"month3ChangePercent":-0.023,"month1ChangePercent":-0.019076,"day30ChangePercent":-0.023,"day5ChangePercent":-0.00963,"nextDividendDate":null,"dividendYield":null,"nextEarningsDate":null,"exDividendDate":null,"peRatio":null,"beta":-0.14733253055795104,"week52highDate":"2020-09-17","week52lowDate":"2020-10-07","EBITDA":null,"currentDebt":null,"debtToEquity":null,"enterpriseValue":null,"enterpriseValueToRevenue":null,"forwardPERatio":null,"grossProfit":null,"pegRatio":null,"priceToBook":null,"priceToSales":null,"profitMargin":null,"revenue":null,"revenuePerEmployee":null,"revenuePerShare":null,"totalCash":null,"totalRevenue":null,"peHigh":null,"peLow":null,"putCallRatio":null} ---> System.Text.Json.JsonException: The JSON value could not be converted to System.Int64. Path: $.employees | LineNumber: 0 | BytePositionInLine: 97. 

I am just going to go ahead and make everything in their nullable just to bullet-proof it.

**Pull request merged**
