### PR TITLE
Feature/stock missing fields

### PR DESCRIPTION
**Pull request by JamiePrentice**
Beginning of picking up missing fields in the response types.

This is just:

- https://iexcloud.io/docs/api/#balance-sheet
- https://iexcloud.io/docs/api/#cash-flow
- https://iexcloud.io/docs/api/#company
- https://iexcloud.io/docs/api/#earnings
- https://iexcloud.io/docs/api/#financials
- https://iexcloud.io/docs/api/#fund-ownership
- https://iexcloud.io/docs/api/#historical-prices
- https://iexcloud.io/docs/api/#insider-summary
- https://iexcloud.io/docs/api/#insider-transactions
- https://iexcloud.io/docs/api/#institutional-ownership
- https://iexcloud.io/docs/api/#key-stats
- https://iexcloud.io/docs/api/#splits-basic

### CODE REVIEW

**Comment by JamiePrentice** [comment]
Will expand on this. Premature PR. Don't merge yet.

**Comment by JamiePrentice** [comment]
With this expansion of fields, looking at https://iexcloud.io/docs/api/#income-statement and IncomeStatementResponse.cs

I'm wondering if it would be safest here to make the majority of the values nullable. Curious about the consensis on this.

**Comment by JamiePrentice** [comment]
```
public string id { get; set; } 
public string key { get; set; } 
public string subkey { get; set; } 
public long updated { get; set; } 
```

Seem to have been added to a lot of the responses, it might be worth looking at a base response that includes these.

**Comment by JamiePrentice** [comment]
There appears to be duplicate fields on Insider-Transactions. 

https://iexcloud.io/docs/api/#insider-transactions

The descriptions of these data points are the same in the API docs, however they appear to be returning different values. This could be down to the fuzzing of data on the test API response however.


image

**Comment by JamiePrentice** [comment]
Ready for review.

These are the updates for under the https://iexcloud.io/docs/api/#stocks-equities section. 

Not including
- https://iexcloud.io/docs/api/#dividends-basic (There's some discrepencies there I don't understand at the moment)
- https://iexcloud.io/docs/api/#financials-as-reported (Not implemented as far as I can see - will do that next)
- https://iexcloud.io/docs/api/#advanced-fundamentals (I think this is the same as above - so will look at doing this too)

**Review by vslee — APPROVED** [review]

**Comment by vslee** [comment]
> With this expansion of fields, looking at https://iexcloud.io/docs/api/#income-statement and IncomeStatementResponse.cs
> 
> I'm wondering if it would be safest here to make the majority of the values nullable. Curious about the consensis on this.

Ya, I think that would be the safest too. 




> ```
> public string id { get; set; } 
> public string key { get; set; } 
> public string subkey { get; set; } 
> public long updated { get; set; } 
> ```
> 
> Seem to have been added to a lot of the responses, it might be worth looking at a base response that includes these.

Sounds good to me



> There appears to be duplicate fields on Insider-Transactions.
> 
> https://iexcloud.io/docs/api/#insider-transactions
> 
> The descriptions of these data points are the same in the API docs, however they appear to be returning different values. This could be down to the fuzzing of data on the test API response however.
> 
> image

You're right, I think it's just the obfuscation they're doing on the sandbox data.

**Pull request merged**
