### PR TITLE
Fixing issues with Dividend (Basic) functionality

### LINKED ISSUE #2: Please support listLimit param in /stock/market/list/{list-type}
/stock/market/list/{list-type}
Please give support all Query String Parameters for this api.
Link: https://iexcloud.io/docs/api/#list

### PR DESCRIPTION
**Pull request by longpshorn**
I ran into a few issues with the Dividend functionality. The DividendFrequency field in the Dividend class was not deserializing correctly because the response from IEXCloud was coming in as "quarterly" (i.e., all lowercase).

I was also seeing an issue when retrieving data for the "Next" dividend because the response from IEXCloud was no longer an array but was an object. I added a new method to the StockFundamentals class to handle this one-off case. I took the same approach with the "Splits" method as well and updated its tests since they were failing since there are no upcoming or prior splits for APPL.

Not sure if these are the most elegant solutions so I am open to feedback on both.

I also removed the EarningsToday method from the StockFundamentals service as it is duplicated in the MarketInfo service. I think that is where it belongs, but let me know if you would prefer to keep it in the StockFundamentals service as well.

Pull request also includes update to address issue #2 which was requesting support for the listLimit query string parameter for the market/list/{listType} endpoint.

Pull request also includes adding of the "Period" parameter to the Estimates method in the StockResearch service.

### CODE REVIEW

**Comment by JamiePrentice** [comment]
>  I was also seeing an issue when retrieving data for the "Next" dividend because the response from IEXCloud was no longer an array but was an object. I added a new method to the StockFundamentals class to handle this one-off case.

I've previously upgraded the C# language version to 8 and changed the method signatures to Dynamic to handle the cases where it could either an IEnumerable<ResponseObject> or a ResponseObject, but that felt... a lot less than elegant. 

As for the AAPL splits, I pulled your branch and tried it with the IEX test company ticker - "ZIEXT" with your test, optimistically hoping it would solve that issue, however that returned "Unknown Symbol" from the API call. :(

**Comment by longpshorn** [comment]
I don't know that using dynamic is less elegant, but it doesn't provide us with much type safety. I think the dynamic in this case may be a better approach since there is no way to prevent someone from calling the IEXSharp api and passing the "Next" option.

**Comment by longpshorn** [comment]
I think I will take a look at switching to the dynamic approach in this pull request and provide and update in a bit.

**Comment by longpshorn** [comment]
Ok, I switched to using the dynamic keyword instead of adding the new methods. I think that is a better approach for now.

**Comment by JamiePrentice** [comment]
> I don't know that using dynamic is less elegant, but it doesn't provide us with much type safety. I think the dynamic in this case may be a better approach since there is no way to prevent someone from calling the IEXSharp api and passing the "Next" option.

The reduced type safety was why I decided against it. 

The only other thing I can think to do right now is adding a special case for the next dividend range like so...  

```csharp
public async Task<IEXResponse<IEnumerable<DividendBasicResponse>>> DividendsBasicAsync(string symbol, DividendRange range)
{
	const string urlPattern = "stock/[symbol]/dividends/[range]";
	var qsb = new QueryStringBuilder();
	var pathNvc = new NameValueCollection
	{
		{"symbol", symbol}, {"range", range.GetDescriptionFromEnum()}
	};

	if (range == DividendRange.Next)
	{
		var dividendResponse = await executor.ExecuteAsync<DividendBasicResponse>(urlPattern, pathNvc, qsb);

		return new IEXResponse<IEnumerable<DividendBasicResponse>>() {
			Data = new List<DividendBasicResponse>{ dividendResponse.Data }
		};
	}

	return await executor.ExecuteAsync<IEnumerable<DividendBasicResponse>>(urlPattern, pathNvc, qsb);
}
```

**Comment by JamiePrentice** [comment]
The alternative would be looking at different ways to do deserialisation, but I'm not sure how much that would impact the rest of the codebase.

**Comment by longpshorn** [comment]
I think the latest proposal you are making is the best. I think that IEXSharp should provide a standardized interface regardless of what IEXCloud provide. Pull Request updated.

**Comment by JamiePrentice** [comment]
I think it's best for now, possibly something we can do better with deserialisation later. Thinking about it, I'm of the opinion that making it dynamic to reduce duplication isn't a fair trade for the loss of type safety.

**Review by vslee — APPROVED** [review]
I personally don't really like dynamic bc it just moves the problem to the user, who then has to do extra work to figure out what the types can be and handle them all. That said, I am only one vote, and if you guys decide later that things are better with dynamic or something else, we can still do that.  
Thanks for also fixing #2.

**Comment by JamiePrentice** [comment]
@vslee I think we're in agreement here. :)

**Comment by longpshorn** [comment]
Yes, definitely in agreement on the dynamic.

**Pull request merged**
