### PR TITLE
Made all Key Stats and Advanced Stats properties nullable and added a…

### PR DESCRIPTION
**Pull request by tmccart1**
… test with a symbol that has many null values (AACQ)

### CODE REVIEW

**Review by JamiePrentice — COMMENTED** [review]
If we were doing this for this response, I'd assume that the next step would be to make all properties nullable on all responses.

@vslee - thoughts on this?

**Comment by tmccart1** [comment]
@JamiePrentice , I agree, it is definitely worth looking into further...I just know that the key stats and advanced stats for certain symbols have lots of null values in them.  @vslee , if we could get this PR in, and then work on the remaining responses I would be really happy -:)  The rest may take a lot of work and lots of added test cases as well, but it would really help to make this library start to become bullet-proof.

**Review by vslee — APPROVED** [review]

**Comment by vslee** [comment]
Unfortunately, since IEX does not document which properties are nullable, we have to resort to this type of solution. I can't think of any other alternative solutions which would be better. Using the default value of a type (say 0 or "") would only make things more confusing for the end user. This solution does now require all end users to check if every value is null, but it allows them to handle things properly on their end, instead of throwing an exception.
@JamiePrentice is right that the logical extension of this solution is to apply it to all endpoints. Seems like a fairly daunting task though.

**Comment by JamiePrentice** [comment]
I'm sure there must be some draw backs and downsides of doing this, but nullable everything isn't something I've played with to any real extent before. I'll do some reading.

And, if that's the way we're going to go, I'm happy to do it.

**Comment by vslee** [comment]
Yes, I look forward to hearing your findings and your conclusion of whether this this or another solution would be better. 

In the meantime, I'm assuming that @tmccart1 has a pressing need for a new NuGet, so I'll release another, unless anyone has anything they want to get in before that?

**Comment by JamiePrentice** [comment]
Nothing pressing from me. Looking forward to writing some code in here again. 👍

**Comment by tmccart1** [comment]
Thank you very much, @vslee !  Yes, I think it would be worth it to basically make every numerical response field nullable.  That is what I ended up doing when I was using Yahoo data...there are always some symbols out there that just end up having a lot of randomly missing data.  When I get time, I will work on that if someone doesn't get to it before me :-)

**Pull request merged**
