### PR TITLE
removed deprecated Legacy endpoints

### PR DESCRIPTION
**Pull request by JamiePrentice**
- Fixed issue with EST Timezone not working on Linux / OSX
- Ignoring tests for deprecated methods.
- Ignoring tests for endpoints that return forbidden. 
- Ignoring tests for endpoints related to IEX listed symbols.

### CODE REVIEW

**Comment by vslee** [comment]
Sorry, I meant ignoring just the two Cloud Deep endpoints. But we can delete the Legacy ones if you want (since those have no hope of ever coming back).

**Comment by JamiePrentice** [comment]
Ah, I didn't realise that I deleted any from the cloud part, I thought I was targeting legacy. I miss-understood, will update this PR with deleting.

**Comment by JamiePrentice** [comment]
Updated.

**Review by vslee — APPROVED** [review]

**Comment by vslee** [comment]
I think the library is now in good shape and we can push a new NuGet. Perhaps I will do that tomm in case any last minute things come up that we'd like to fix?

**Comment by JamiePrentice** [comment]
That’s a good idea. I think it’s due a release. We should verify we’ve not missed any cloud endpoints, but that should be much easier now that they’re grouped the same way as the IEX documentation. 

There’s definitely breaking changes in this compared to the last release, so it might be worth a major version number bump.

**Comment by vslee** [comment]
Okay, the next one will be 2.0

**Pull request merged**
